// ═══════════════════════════════════════════
// LOCAL FALLBACK DATABASE (values per 100 g)
// ═══════════════════════════════════════════
var LOCAL_FOODS = [
  {
    name: "Kuřecí prsa",
    cat: "Maso",
    kcal: 110,
    protein: 23,
    carbs: 0,
    fat: 1.3,
    measurements: [
      { name: "porce (150 g)", grams: 150 },
      { name: "velká porce (200 g)", grams: 200 },
    ],
  },
  {
    name: "Kuřecí stehno",
    cat: "Maso",
    kcal: 177,
    protein: 18,
    carbs: 0,
    fat: 11,
    measurements: [{ name: "kus (130 g)", grams: 130 }],
  },
  {
    name: "Hovězí svíčková",
    cat: "Maso",
    kcal: 121,
    protein: 21,
    carbs: 0,
    fat: 4,
    measurements: [{ name: "porce (150 g)", grams: 150 }],
  },
  {
    name: "Hovězí mleté",
    cat: "Maso",
    kcal: 254,
    protein: 17,
    carbs: 0,
    fat: 20,
    measurements: [{ name: "porce (150 g)", grams: 150 }],
  },
  {
    name: "Vepřová kotleta",
    cat: "Maso",
    kcal: 242,
    protein: 19,
    carbs: 0,
    fat: 18,
    measurements: [{ name: "kus (150 g)", grams: 150 }],
  },
  {
    name: "Vepřová panenka",
    cat: "Maso",
    kcal: 143,
    protein: 21,
    carbs: 0,
    fat: 6,
    measurements: [{ name: "porce (150 g)", grams: 150 }],
  },
  {
    name: "Krůtí prsa",
    cat: "Maso",
    kcal: 104,
    protein: 24,
    carbs: 0,
    fat: 0.7,
    measurements: [
      { name: "porce (150 g)", grams: 150 },
      { name: "velká porce (200 g)", grams: 200 },
    ],
  },
  {
    name: "Losos",
    cat: "Maso",
    kcal: 208,
    protein: 20,
    carbs: 0,
    fat: 13,
    measurements: [
      { name: "filet (125 g)", grams: 125 },
      { name: "porce (150 g)", grams: 150 },
    ],
  },
  {
    name: "Tuňák (konzerva)",
    cat: "Maso",
    kcal: 116,
    protein: 26,
    carbs: 0,
    fat: 1,
    measurements: [
      { name: "malá konzerva (80 g)", grams: 80 },
      { name: "konzerva (150 g)", grams: 150 },
    ],
  },
  {
    name: "Treska",
    cat: "Maso",
    kcal: 82,
    protein: 18,
    carbs: 0,
    fat: 0.7,
    measurements: [{ name: "filet (150 g)", grams: 150 }],
  },
  {
    name: "Šunka",
    cat: "Maso",
    kcal: 145,
    protein: 18,
    carbs: 1,
    fat: 7,
    measurements: [{ name: "plátek (25 g)", grams: 25 }],
  },
  {
    name: "Mléko 1.5%",
    cat: "Mléčné",
    kcal: 47,
    protein: 3.4,
    carbs: 4.9,
    fat: 1.5,
    liquid: true,
    measurements: [
      { name: "sklenice (250 ml)", grams: 250 },
      { name: "malá sklenice (200 ml)", grams: 200 },
    ],
  },
  {
    name: "Jogurt bílý",
    cat: "Mléčné",
    kcal: 63,
    protein: 5,
    carbs: 4,
    fat: 3,
    liquid: true,
    measurements: [
      { name: "kelímek (150 g)", grams: 150 },
      { name: "velký kelímek (200 g)", grams: 200 },
    ],
  },
  {
    name: "Řecký jogurt",
    cat: "Mléčné",
    kcal: 97,
    protein: 9,
    carbs: 3.6,
    fat: 5,
    liquid: true,
    measurements: [
      { name: "kelímek (150 g)", grams: 150 },
      { name: "velký kelímek (200 g)", grams: 200 },
    ],
  },
  {
    name: "Skyr",
    cat: "Mléčné",
    kcal: 63,
    protein: 11,
    carbs: 4,
    fat: 0.2,
    liquid: true,
    measurements: [
      { name: "kelímek (150 g)", grams: 150 },
      { name: "velký kelímek (400 g)", grams: 400 },
    ],
  },
  {
    name: "Tvaroh měkký",
    cat: "Mléčné",
    kcal: 98,
    protein: 13,
    carbs: 3.5,
    fat: 4,
    measurements: [{ name: "balení (250 g)", grams: 250 }],
  },
  {
    name: "Cottage cheese",
    cat: "Mléčné",
    kcal: 98,
    protein: 11,
    carbs: 3.4,
    fat: 4.3,
    measurements: [{ name: "balení (150 g)", grams: 150 }],
  },
  {
    name: "Eidam 30%",
    cat: "Mléčné",
    kcal: 260,
    protein: 30,
    carbs: 0,
    fat: 15,
    measurements: [{ name: "plátek (30 g)", grams: 30 }],
  },
  {
    name: "Mozzarella",
    cat: "Mléčné",
    kcal: 280,
    protein: 22,
    carbs: 2,
    fat: 20,
    measurements: [{ name: "balení (125 g)", grams: 125 }],
  },
  {
    name: "Máslo",
    cat: "Mléčné",
    kcal: 717,
    protein: 0.9,
    carbs: 0.1,
    fat: 81,
    measurements: [
      { name: "porce (10 g)", grams: 10 },
      { name: "balení (250 g)", grams: 250 },
    ],
  },
  {
    name: "Chleba žitný",
    cat: "Pečivo",
    kcal: 220,
    protein: 7,
    carbs: 43,
    fat: 1.2,
    measurements: [{ name: "krajíc (60 g)", grams: 60 }],
  },
  {
    name: "Rohlík",
    cat: "Pečivo",
    kcal: 280,
    protein: 8,
    carbs: 52,
    fat: 3.5,
    measurements: [{ name: "kus (43 g)", grams: 43 }],
  },
  {
    name: "Celozrnný chléb",
    cat: "Pečivo",
    kcal: 210,
    protein: 9,
    carbs: 38,
    fat: 2.5,
    measurements: [{ name: "krajíc (60 g)", grams: 60 }],
  },
  {
    name: "Ovesné vločky",
    cat: "Pečivo",
    kcal: 367,
    protein: 13,
    carbs: 56,
    fat: 7,
    measurements: [
      { name: "porce (40 g)", grams: 40 },
      { name: "velká porce (60 g)", grams: 60 },
    ],
  },
  {
    name: "Rýže bílá (vařená)",
    cat: "Pečivo",
    kcal: 130,
    protein: 2.7,
    carbs: 28,
    fat: 0.3,
    measurements: [
      { name: "porce (150 g)", grams: 150 },
      { name: "velká porce (200 g)", grams: 200 },
    ],
  },
  {
    name: "Těstoviny (vařené)",
    cat: "Pečivo",
    kcal: 131,
    protein: 5,
    carbs: 25,
    fat: 1.1,
    measurements: [
      { name: "porce (200 g)", grams: 200 },
      { name: "velká porce (250 g)", grams: 250 },
    ],
  },
  {
    name: "Jablko",
    cat: "Ovoce",
    kcal: 52,
    protein: 0.3,
    carbs: 14,
    fat: 0.2,
    measurements: [
      { name: "malé (150 g)", grams: 150 },
      { name: "velké (200 g)", grams: 200 },
    ],
  },
  {
    name: "Banán",
    cat: "Ovoce",
    kcal: 89,
    protein: 1.1,
    carbs: 23,
    fat: 0.3,
    measurements: [
      { name: "malý (100 g)", grams: 100 },
      { name: "velký (130 g)", grams: 130 },
    ],
  },
  {
    name: "Pomeranč",
    cat: "Ovoce",
    kcal: 47,
    protein: 0.9,
    carbs: 12,
    fat: 0.1,
    measurements: [{ name: "kus (180 g)", grams: 180 }],
  },
  {
    name: "Jahody",
    cat: "Ovoce",
    kcal: 32,
    protein: 0.7,
    carbs: 8,
    fat: 0.3,
    measurements: [{ name: "miska (150 g)", grams: 150 }],
  },
  {
    name: "Avokádo",
    cat: "Ovoce",
    kcal: 160,
    protein: 2,
    carbs: 9,
    fat: 15,
    measurements: [
      { name: "kus (150 g)", grams: 150 },
      { name: "půlka (75 g)", grams: 75 },
    ],
  },
  {
    name: "Brambory (vařené)",
    cat: "Zelenina",
    kcal: 77,
    protein: 2,
    carbs: 17,
    fat: 0.1,
    measurements: [
      { name: "porce (200 g)", grams: 200 },
      { name: "kus (80 g)", grams: 80 },
    ],
  },
  {
    name: "Rajče",
    cat: "Zelenina",
    kcal: 18,
    protein: 0.9,
    carbs: 3.9,
    fat: 0.2,
    measurements: [{ name: "kus (120 g)", grams: 120 }],
  },
  {
    name: "Okurka",
    cat: "Zelenina",
    kcal: 12,
    protein: 0.6,
    carbs: 2,
    fat: 0.1,
    measurements: [{ name: "kus (300 g)", grams: 300 }],
  },
  {
    name: "Paprika",
    cat: "Zelenina",
    kcal: 27,
    protein: 1,
    carbs: 6,
    fat: 0.3,
    measurements: [{ name: "kus (150 g)", grams: 150 }],
  },
  {
    name: "Brokolice",
    cat: "Zelenina",
    kcal: 34,
    protein: 2.8,
    carbs: 7,
    fat: 0.4,
    measurements: [{ name: "porce (150 g)", grams: 150 }],
  },
  {
    name: "Čočka (vařená)",
    cat: "Luštěniny",
    kcal: 116,
    protein: 9,
    carbs: 20,
    fat: 0.4,
    measurements: [{ name: "porce (150 g)", grams: 150 }],
  },
  {
    name: "Cizrna (vařená)",
    cat: "Luštěniny",
    kcal: 164,
    protein: 9,
    carbs: 27,
    fat: 2.6,
    measurements: [{ name: "porce (150 g)", grams: 150 }],
  },
  {
    name: "Arašídy",
    cat: "Luštěniny",
    kcal: 567,
    protein: 26,
    carbs: 16,
    fat: 49,
    measurements: [{ name: "hrst (30 g)", grams: 30 }],
  },
  {
    name: "Mandle",
    cat: "Luštěniny",
    kcal: 579,
    protein: 21,
    carbs: 22,
    fat: 50,
    measurements: [{ name: "hrst (30 g)", grams: 30 }],
  },
  {
    name: "Čokoláda mléčná",
    cat: "Sladkosti",
    kcal: 535,
    protein: 8,
    carbs: 56,
    fat: 30,
    measurements: [
      { name: "řádka (25 g)", grams: 25 },
      { name: "tabulka (100 g)", grams: 100 },
    ],
  },
  {
    name: "Med",
    cat: "Sladkosti",
    kcal: 304,
    protein: 0.3,
    carbs: 82,
    fat: 0,
    measurements: [
      { name: "lžička (8 g)", grams: 8 },
      { name: "lžíce (20 g)", grams: 20 },
    ],
  },
  {
    name: "Chipsy",
    cat: "Sladkosti",
    kcal: 536,
    protein: 7,
    carbs: 53,
    fat: 33,
    measurements: [{ name: "balení (150 g)", grams: 150 }],
  },
  {
    name: "Vejce",
    cat: "Ostatní",
    kcal: 142,
    protein: 11.5,
    carbs: 1.1,
    fat: 9.6,
    measurements: [
      { name: "velký kus (60 g)", grams: 60 },
      { name: "kus (55 g)", grams: 55 },
      { name: "malý kus (50 g)", grams: 50 },
    ],
  },
  {
    name: "Olivový olej",
    cat: "Ostatní",
    kcal: 884,
    protein: 0,
    carbs: 0,
    fat: 100,
    measurements: [
      { name: "lžíce (14 g)", grams: 14 },
      { name: "lžička (5 g)", grams: 5 },
    ],
  },
  {
    name: "Protein whey",
    cat: "Ostatní",
    kcal: 400,
    protein: 80,
    carbs: 10,
    fat: 5,
    measurements: [{ name: "odměrka (30 g)", grams: 30 }],
  },
  {
    name: "Svíčková na smetaně",
    cat: "Česká jídla",
    kcal: 195,
    protein: 12,
    carbs: 15,
    fat: 9,
    measurements: [{ name: "porce (300 g)", grams: 300 }],
  },
  {
    name: "Knedlo-vepřo-zelo",
    cat: "Česká jídla",
    kcal: 220,
    protein: 13,
    carbs: 22,
    fat: 9,
    measurements: [{ name: "porce (350 g)", grams: 350 }],
  },
  {
    name: "Smažený sýr",
    cat: "Česká jídla",
    kcal: 320,
    protein: 16,
    carbs: 15,
    fat: 22,
    measurements: [{ name: "kus (150 g)", grams: 150 }],
  },
  {
    name: "Guláš hovězí",
    cat: "Česká jídla",
    kcal: 135,
    protein: 14,
    carbs: 6,
    fat: 6,
    measurements: [{ name: "porce (300 g)", grams: 300 }],
  },
  {
    name: "Řízek vepřový",
    cat: "Česká jídla",
    kcal: 265,
    protein: 17,
    carbs: 14,
    fat: 16,
    measurements: [{ name: "kus (150 g)", grams: 150 }],
  },
  {
    name: "Palačinky",
    cat: "Česká jídla",
    kcal: 227,
    protein: 6,
    carbs: 28,
    fat: 10,
    measurements: [{ name: "kus (60 g)", grams: 60 }],
  },
];

